// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqeM4_hoxao7j6GTJ3Km1DuIqvDdbq1oM',
    appId: '1:359937070047:web:0a36cc7313ea81ac5d2a6a',
    messagingSenderId: '359937070047',
    projectId: 'focusfox-cc167',
    authDomain: 'focusfox-cc167.firebaseapp.com',
    storageBucket: 'focusfox-cc167.firebasestorage.app',
    measurementId: 'G-ZVCTWZGNYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKoJlyLVR0O4KEAUSYqNuAfZ4i8uz_Kmk',
    appId: '1:359937070047:android:5ee191b5e1d6bcfa5d2a6a',
    messagingSenderId: '359937070047',
    projectId: 'focusfox-cc167',
    storageBucket: 'focusfox-cc167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDv9ZV8ImEgL_68VRhKPnotj5V9c9KjVc',
    appId: '1:359937070047:ios:729bda84dac60a4b5d2a6a',
    messagingSenderId: '359937070047',
    projectId: 'focusfox-cc167',
    storageBucket: 'focusfox-cc167.firebasestorage.app',
    iosBundleId: 'com.focusfox.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDv9ZV8ImEgL_68VRhKPnotj5V9c9KjVc',
    appId: '1:359937070047:ios:729bda84dac60a4b5d2a6a',
    messagingSenderId: '359937070047',
    projectId: 'focusfox-cc167',
    storageBucket: 'focusfox-cc167.firebasestorage.app',
    iosBundleId: 'com.focusfox.study',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqeM4_hoxao7j6GTJ3Km1DuIqvDdbq1oM',
    appId: '1:359937070047:web:385a2a878b2cf1fa5d2a6a',
    messagingSenderId: '359937070047',
    projectId: 'focusfox-cc167',
    authDomain: 'focusfox-cc167.firebaseapp.com',
    storageBucket: 'focusfox-cc167.firebasestorage.app',
    measurementId: 'G-Y03W7QJ3PP',
  );
}
